import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Col, Container, Row } from 'react-bootstrap';
import Tariffs from '../components/Tariffs/Tariffs';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Result List App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container fluid>
        <Row>
          <Col>
            <Tariffs />
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export default Home;
